-- 億家 App v0.10.9.0
-- 點數兌換 + App 點數折抵
-- 請在 Supabase SQL Editor 執行一次。

create table if not exists public.app_member_point_rewards (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  member_phone text not null,
  reward_id text not null,
  reward_name text not null,
  reward_type text not null default 'reward',
  reward_snapshot jsonb not null default '{}'::jsonb,
  points_used integer not null check (points_used > 0),
  status text not null default 'available',
  redeemed_at timestamptz not null default now(),
  valid_until timestamptz,
  used_at timestamptz
);

create index if not exists idx_app_member_point_rewards_auth
  on public.app_member_point_rewards(auth_user_id, redeemed_at desc);

alter table public.app_member_point_rewards enable row level security;
revoke all on public.app_member_point_rewards from anon, authenticated;


create table if not exists public.app_point_discount_tickets (
  id bigint generated by default as identity primary key,
  discount_code text not null unique,
  auth_user_id uuid not null,
  member_phone text not null,
  points integer not null check (points > 0),
  discount_amount integer not null check (discount_amount > 0),
  status text not null default 'pending',
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  used_at timestamptz,
  used_store_code text,
  tm_sale_id text
);

create index if not exists idx_app_point_discount_tickets_auth
  on public.app_point_discount_tickets(auth_user_id, created_at desc);

create index if not exists idx_app_point_discount_tickets_code
  on public.app_point_discount_tickets(discount_code, status);

alter table public.app_point_discount_tickets enable row level security;
revoke all on public.app_point_discount_tickets from anon, authenticated;


-- 讀取總部 SC 未來可維護的點數兌換商品。
-- data_key 固定：yj_app_point_rewards
-- 支援 data 直接為 array，或 {"rewards":[...]}。
create or replace function public.app_get_point_rewards()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_data jsonb;
  v_rows jsonb;
begin
  select data into v_data
  from public.yijia_app_state
  where store_id = 'HQ'
    and data_key = 'yj_app_point_rewards'
  limit 1;

  if v_data is null then
    return '[]'::jsonb;
  end if;

  if jsonb_typeof(v_data) = 'array' then
    v_rows := v_data;
  elsif jsonb_typeof(v_data->'rewards') = 'array' then
    v_rows := v_data->'rewards';
  else
    return '[]'::jsonb;
  end if;

  return coalesce((
    select jsonb_agg(x order by coalesce((x->>'sortOrder')::integer,9999), x->>'name')
    from jsonb_array_elements(v_rows) x
    where coalesce((x->>'active')::boolean,true) = true
      and coalesce((x->>'enabled')::boolean,true) = true
  ), '[]'::jsonb);
end;
$$;


create or replace function public.app_redeem_point_reward(
  p_reward_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_phone text;
  v_points public.app_points%rowtype;
  v_rewards jsonb;
  v_reward jsonb;
  v_cost integer;
  v_name text;
  v_valid_days integer;
  v_valid_until timestamptz;
  v_expiring_used integer;
  v_reward_id text;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  select phone into v_phone
  from public.app_members
  where auth_user_id = v_uid
  limit 1;

  if coalesce(v_phone,'') = '' then
    raise exception 'member not found';
  end if;

  v_rewards := public.app_get_point_rewards();

  select x into v_reward
  from jsonb_array_elements(v_rewards) x
  where coalesce(x->>'rewardId',x->>'id',x->>'code') = p_reward_id
  limit 1;

  if v_reward is null then
    raise exception 'point reward not found';
  end if;

  v_reward_id := coalesce(v_reward->>'rewardId',v_reward->>'id',v_reward->>'code');
  v_name := coalesce(v_reward->>'name','點數兌換');
  v_cost := coalesce(
    nullif(v_reward->>'pointsCost','')::integer,
    nullif(v_reward->>'points','')::integer,
    nullif(v_reward->>'costPoints','')::integer,
    0
  );

  if v_cost <= 0 then
    raise exception 'invalid reward points cost';
  end if;

  select * into v_points
  from public.app_points
  where auth_user_id = v_uid
  for update;

  if v_points.id is null then
    raise exception 'point account not found';
  end if;

  if coalesce(v_points.available_points,0) < v_cost then
    raise exception 'insufficient points';
  end if;

  v_expiring_used := least(coalesce(v_points.expiring_points,0), v_cost);

  update public.app_points
  set available_points = available_points - v_cost,
      expiring_points = greatest(0, coalesce(expiring_points,0) - v_expiring_used),
      updated_at = now()
  where id = v_points.id;

  v_valid_days := coalesce(nullif(v_reward->>'validityDays','')::integer, 30);
  if v_valid_days > 0 then
    v_valid_until := now() + make_interval(days => v_valid_days);
  end if;

  insert into public.app_point_transactions(
    phone, transaction_type, points, description, created_at, auth_user_id
  )
  values(
    v_phone,
    'reward_redeem',
    -v_cost,
    '點數兌換：' || v_name,
    now(),
    v_uid
  );

  insert into public.app_member_point_rewards(
    auth_user_id,
    member_phone,
    reward_id,
    reward_name,
    reward_type,
    reward_snapshot,
    points_used,
    status,
    redeemed_at,
    valid_until
  )
  values(
    v_uid,
    v_phone,
    v_reward_id,
    v_name,
    coalesce(v_reward->>'rewardType','reward'),
    v_reward,
    v_cost,
    'available',
    now(),
    v_valid_until
  );

  return jsonb_build_object(
    'ok', true,
    'rewardId', v_reward_id,
    'rewardName', v_name,
    'pointsUsed', v_cost,
    'remainingPoints', v_points.available_points - v_cost,
    'validUntil', v_valid_until
  );
end;
$$;


create or replace function public.app_get_my_point_rewards()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', r.id,
    'rewardId', r.reward_id,
    'rewardName', r.reward_name,
    'rewardType', r.reward_type,
    'pointsUsed', r.points_used,
    'status', r.status,
    'redeemedAt', r.redeemed_at,
    'validUntil', r.valid_until,
    'usedAt', r.used_at,
    'snapshot', r.reward_snapshot
  ) order by r.redeemed_at desc),'[]'::jsonb)
  from public.app_member_point_rewards r
  where r.auth_user_id = auth.uid();
$$;


-- 建立 App 點數折抵 QR。
-- 預設 1 點 = $1；總部可在 yj_hq_app_settings.data.appBackend 設定：
-- pointDiscountPointsPerDollar
-- pointDiscountMinPoints
-- pointDiscountStep
-- pointDiscountMaxPoints (0 = 不限)
-- pointDiscountEnabled
create or replace function public.app_create_point_discount_ticket(
  p_points integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_phone text;
  v_available integer;
  v_backend jsonb;
  v_ratio integer := 1;
  v_min integer := 1;
  v_step integer := 1;
  v_max integer := 0;
  v_enabled boolean := true;
  v_amount integer;
  v_code text;
  v_expires timestamptz := now() + interval '600 seconds';
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  select phone into v_phone
  from public.app_members
  where auth_user_id = v_uid
  limit 1;

  if coalesce(v_phone,'') = '' then
    raise exception 'member not found';
  end if;

  select available_points into v_available
  from public.app_points
  where auth_user_id = v_uid
  limit 1;

  if v_available is null then
    raise exception 'point account not found';
  end if;

  select coalesce(data->'appBackend', data->'backend', data)
    into v_backend
  from public.yijia_app_state
  where store_id='001'
    and data_key='yj_hq_app_settings'
  limit 1;

  if v_backend is not null then
    v_enabled := coalesce((v_backend->>'pointDiscountEnabled')::boolean,true);
    v_ratio := greatest(1,coalesce(nullif(v_backend->>'pointDiscountPointsPerDollar','')::integer,1));
    v_min := greatest(1,coalesce(nullif(v_backend->>'pointDiscountMinPoints','')::integer,1));
    v_step := greatest(1,coalesce(nullif(v_backend->>'pointDiscountStep','')::integer,1));
    v_max := greatest(0,coalesce(nullif(v_backend->>'pointDiscountMaxPoints','')::integer,0));
  end if;

  if not v_enabled then
    raise exception 'point discount disabled';
  end if;

  if p_points is null or p_points < v_min then
    raise exception 'points below minimum';
  end if;

  if mod(p_points,v_step) <> 0 then
    raise exception 'points must match step';
  end if;

  if v_max > 0 and p_points > v_max then
    raise exception 'points exceed maximum';
  end if;

  if p_points > v_available then
    raise exception 'insufficient points';
  end if;

  v_amount := floor(p_points::numeric / v_ratio)::integer;
  if v_amount <= 0 then
    raise exception 'discount amount is zero';
  end if;

  -- 同會員只保留最新一張 pending 折抵碼。
  update public.app_point_discount_tickets
  set status='cancelled'
  where auth_user_id=v_uid
    and status='pending';

  loop
    v_code :=
      'YPD'
      || to_char(clock_timestamp() at time zone 'Asia/Taipei','YYMMDDHH24MISSMS')
      || lpad((floor(random()*10000))::integer::text,4,'0');

    exit when not exists(
      select 1 from public.app_point_discount_tickets where discount_code=v_code
    );
  end loop;

  insert into public.app_point_discount_tickets(
    discount_code,
    auth_user_id,
    member_phone,
    points,
    discount_amount,
    status,
    expires_at
  )
  values(
    v_code,
    v_uid,
    v_phone,
    p_points,
    v_amount,
    'pending',
    v_expires
  );

  return jsonb_build_object(
    'discountCode', v_code,
    'memberPhone', v_phone,
    'points', p_points,
    'discountAmount', v_amount,
    'expiresAt', v_expires,
    'status', 'pending'
  );
end;
$$;


create or replace function public.tm_get_point_discount_ticket(
  p_discount_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.app_point_discount_tickets%rowtype;
begin
  select * into v_row
  from public.app_point_discount_tickets
  where discount_code=trim(p_discount_code)
  limit 1;

  if v_row.id is null then
    raise exception 'point discount ticket not found';
  end if;

  if v_row.status <> 'pending' then
    raise exception 'point discount ticket unavailable';
  end if;

  if v_row.expires_at <= now() then
    update public.app_point_discount_tickets
    set status='expired'
    where id=v_row.id;
    raise exception 'point discount ticket expired';
  end if;

  return jsonb_build_object(
    'discountCode', v_row.discount_code,
    'memberPhone', v_row.member_phone,
    'points', v_row.points,
    'discountAmount', v_row.discount_amount,
    'expiresAt', v_row.expires_at,
    'status', v_row.status
  );
end;
$$;


-- TM 必須在整筆一般商品交易成功後才呼叫此函式。
-- 這一步才正式扣點，避免掃碼後交易取消卻先扣點。
create or replace function public.tm_complete_point_discount_ticket(
  p_discount_code text,
  p_store_code text,
  p_tm_sale_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.app_point_discount_tickets%rowtype;
  v_points public.app_points%rowtype;
  v_expiring_used integer;
begin
  select * into v_row
  from public.app_point_discount_tickets
  where discount_code=trim(p_discount_code)
  for update;

  if v_row.id is null then
    raise exception 'point discount ticket not found';
  end if;

  if v_row.status='used' then
    raise exception 'point discount ticket already used';
  end if;

  if v_row.status <> 'pending' then
    raise exception 'point discount ticket unavailable';
  end if;

  if v_row.expires_at <= now() then
    update public.app_point_discount_tickets
    set status='expired'
    where id=v_row.id;
    raise exception 'point discount ticket expired';
  end if;

  select * into v_points
  from public.app_points
  where auth_user_id=v_row.auth_user_id
  for update;

  if v_points.id is null then
    raise exception 'point account not found';
  end if;

  if coalesce(v_points.available_points,0) < v_row.points then
    raise exception 'insufficient points';
  end if;

  v_expiring_used := least(coalesce(v_points.expiring_points,0),v_row.points);

  update public.app_points
  set available_points=available_points-v_row.points,
      expiring_points=greatest(0,coalesce(expiring_points,0)-v_expiring_used),
      updated_at=now()
  where id=v_points.id;

  insert into public.app_point_transactions(
    phone, transaction_type, points, description, created_at, auth_user_id
  )
  values(
    v_row.member_phone,
    'discount',
    -v_row.points,
    '點數折抵：$' || v_row.discount_amount::text || '（TM ' || coalesce(p_tm_sale_id,'') || '）',
    now(),
    v_row.auth_user_id
  );

  update public.app_point_discount_tickets
  set status='used',
      used_at=now(),
      used_store_code=p_store_code,
      tm_sale_id=p_tm_sale_id
  where id=v_row.id;

  return jsonb_build_object(
    'ok',true,
    'discountCode',v_row.discount_code,
    'pointsUsed',v_row.points,
    'discountAmount',v_row.discount_amount,
    'remainingPoints',v_points.available_points-v_row.points,
    'usedAt',now()
  );
end;
$$;


grant execute on function public.app_get_point_rewards() to authenticated;
grant execute on function public.app_redeem_point_reward(text) to authenticated;
grant execute on function public.app_get_my_point_rewards() to authenticated;
grant execute on function public.app_create_point_discount_ticket(integer) to authenticated;
grant execute on function public.tm_get_point_discount_ticket(text) to authenticated;
grant execute on function public.tm_complete_point_discount_ticket(text,text,text) to authenticated;

notify pgrst, 'reload schema';
