-- 億家 App v0.10.9.1 Points Sync
-- 目的：
-- 1. App 不再自己維護點數折抵比例。
-- 2. 直接使用既有 TM / SC 的 app_point_feature_settings：
--    redeem_unit_points = 折抵所需點數
--    redeem_unit_amount = 可折抵金額
-- 3. 修復 v0.10.9.0 曾覆蓋的 app_get_point_rewards()。
-- 4. YPD 折抵 QR 也完全使用同一套設定。
--
-- 目前既有規則可為：300 點折 1 元。
-- 若後台日後修改，App 會自動同步，不需再改 App。

begin;

-- =========================================================
-- A. 恢復既有 TM / SC 點數兌換商品來源
-- =========================================================
create or replace function public.app_get_point_rewards()
returns jsonb
language sql
security definer
set search_path=public
as $$
  select coalesce(
    jsonb_agg(to_jsonb(r) order by r.sort_order, r.created_at desc),
    '[]'::jsonb
  )
  from public.app_point_rewards r
  cross join public.app_point_feature_settings s
  where s.id='default'
    and s.reward_enabled=true
    and r.active=true
    and (r.starts_at is null or r.starts_at<=now())
    and (r.ends_at is null or r.ends_at>=now())
    and (r.stock_limit is null or r.redeemed_qty<r.stock_limit);
$$;

revoke all on function public.app_get_point_rewards() from public;
grant execute on function public.app_get_point_rewards() to authenticated;

-- v0.10.9.0 額外建立的文字版兌換函式不再使用，避免與正式 TM 9.02 版本混淆。
drop function if exists public.app_redeem_point_reward(text);

-- =========================================================
-- B. YPD 點數折抵票
-- =========================================================
create table if not exists public.app_point_discount_tickets (
  id bigint generated by default as identity primary key,
  discount_code text not null unique,
  auth_user_id uuid not null,
  member_phone text not null,
  member_no text,
  points integer not null check (points > 0),
  discount_amount numeric(12,2) not null check (discount_amount > 0),
  status text not null default 'pending',
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  used_at timestamptz,
  used_store_code text,
  tm_sale_id text
);

alter table public.app_point_discount_tickets
  add column if not exists member_no text;

create index if not exists idx_app_point_discount_tickets_auth
  on public.app_point_discount_tickets(auth_user_id, created_at desc);

create index if not exists idx_app_point_discount_tickets_code
  on public.app_point_discount_tickets(discount_code, status);

alter table public.app_point_discount_tickets enable row level security;
revoke all on public.app_point_discount_tickets from anon, authenticated;

-- =========================================================
-- C. App 建立折抵 QR
--    只「保留」點數，不在此時正式扣點。
-- =========================================================
create or replace function public.app_create_point_discount_ticket(
  p_points integer
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid := auth.uid();
  v_cfg public.app_point_feature_settings%rowtype;
  v_m jsonb;
  v_phone text;
  v_member_no text;
  v_available integer := 0;
  v_units integer := 0;
  v_amount numeric(12,2) := 0;
  v_code text;
  v_expires timestamptz := now() + interval '600 seconds';
begin
  if v_uid is null then
    raise exception 'authentication required';
  end if;

  select * into v_cfg
  from public.app_point_feature_settings
  where id='default';

  if not found then
    raise exception 'point feature settings not found';
  end if;

  if not coalesce(v_cfg.discount_enabled,false) then
    raise exception 'point discount feature disabled';
  end if;

  if p_points is null or p_points<=0 then
    raise exception 'invalid points';
  end if;

  if mod(p_points,v_cfg.redeem_unit_points)<>0 then
    raise exception
      'points must be a multiple of %',
      v_cfg.redeem_unit_points;
  end if;

  select coalesce(available_points,0)
    into v_available
  from public.app_points
  where auth_user_id=v_uid;

  if coalesce(v_available,0)<p_points then
    raise exception 'insufficient points';
  end if;

  v_units := p_points / v_cfg.redeem_unit_points;
  v_amount := round(v_units * v_cfg.redeem_unit_amount,2);

  if v_amount<=0 then
    raise exception 'discount amount is zero';
  end if;

  v_m := public.app_current_member_json();
  v_phone := regexp_replace(
    coalesce(v_m->>'memberPhone',''),
    '[^0-9]','','g'
  );
  v_member_no := coalesce(v_m->>'memberNo','');

  if v_phone='' then
    raise exception 'member phone not found';
  end if;

  -- 同會員只保留最新一張尚未使用的 YPD。
  update public.app_point_discount_tickets
  set status='cancelled'
  where auth_user_id=v_uid
    and status='pending';

  loop
    v_code :=
      'YPD'
      || to_char(
        clock_timestamp() at time zone 'Asia/Taipei',
        'YYMMDDHH24MISSMS'
      )
      || lpad(
        (floor(random()*10000))::integer::text,
        4,'0'
      );

    exit when not exists(
      select 1
      from public.app_point_discount_tickets
      where discount_code=v_code
    );
  end loop;

  insert into public.app_point_discount_tickets(
    discount_code,
    auth_user_id,
    member_phone,
    member_no,
    points,
    discount_amount,
    status,
    expires_at
  )
  values(
    v_code,
    v_uid,
    v_phone,
    v_member_no,
    p_points,
    v_amount,
    'pending',
    v_expires
  );

  return jsonb_build_object(
    'discountCode',v_code,
    'memberPhone',v_phone,
    'memberNo',v_member_no,
    'points',p_points,
    'discountAmount',v_amount,
    'unitPoints',v_cfg.redeem_unit_points,
    'unitAmount',v_cfg.redeem_unit_amount,
    'expiresAt',v_expires,
    'status','pending'
  );
end;
$$;

-- =========================================================
-- D. TM 掃描 YPD：只讀取，不扣點
-- =========================================================
create or replace function public.tm_get_point_discount_ticket(
  p_discount_code text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_row public.app_point_discount_tickets%rowtype;
  v_cfg public.app_point_feature_settings%rowtype;
  v_available integer := 0;
begin
  select * into v_row
  from public.app_point_discount_tickets
  where discount_code=trim(p_discount_code)
  limit 1;

  if v_row.id is null then
    raise exception 'point discount ticket not found';
  end if;

  if v_row.status<>'pending' then
    raise exception 'point discount ticket unavailable';
  end if;

  if v_row.expires_at<=now() then
    update public.app_point_discount_tickets
    set status='expired'
    where id=v_row.id;

    raise exception 'point discount ticket expired';
  end if;

  select * into v_cfg
  from public.app_point_feature_settings
  where id='default';

  if not coalesce(v_cfg.discount_enabled,false) then
    raise exception 'point discount feature disabled';
  end if;

  select coalesce(available_points,0)
    into v_available
  from public.app_points
  where auth_user_id=v_row.auth_user_id;

  if v_available<v_row.points then
    raise exception 'insufficient points';
  end if;

  return jsonb_build_object(
    'discountCode',v_row.discount_code,
    'memberPhone',v_row.member_phone,
    'memberNo',v_row.member_no,
    'points',v_row.points,
    'discountAmount',v_row.discount_amount,
    'maxDiscountPercent',v_cfg.max_discount_percent,
    'minOrderAmount',v_cfg.min_order_amount,
    'expiresAt',v_row.expires_at,
    'status',v_row.status
  );
end;
$$;

-- =========================================================
-- E. TM 交易成功後才正式扣點
--    使用既有 tm_sync_member_points()，
--    因此 TM / SC / App 點數會走同一套同步核心。
-- =========================================================
create or replace function public.tm_complete_point_discount_ticket(
  p_discount_code text,
  p_store_code text,
  p_tm_sale_id text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_row public.app_point_discount_tickets%rowtype;
  v_sync jsonb;
begin
  select * into v_row
  from public.app_point_discount_tickets
  where discount_code=trim(p_discount_code)
  for update;

  if v_row.id is null then
    raise exception 'point discount ticket not found';
  end if;

  if v_row.status='used' then
    raise exception 'point discount ticket already used';
  end if;

  if v_row.status<>'pending' then
    raise exception 'point discount ticket unavailable';
  end if;

  if v_row.expires_at<=now() then
    update public.app_point_discount_tickets
    set status='expired'
    where id=v_row.id;

    raise exception 'point discount ticket expired';
  end if;

  -- 正式扣點：直接走既有 TM 點數同步核心。
  v_sync := public.tm_sync_member_points(
    v_row.member_phone,
    coalesce(v_row.member_no,''),
    -v_row.points,
    'discount',
    'APP-DISCOUNT:'||v_row.discount_code,
    'App 點數折抵｜$'||v_row.discount_amount::text,
    coalesce(p_tm_sale_id,'')
  );

  update public.app_point_discount_tickets
  set status='used',
      used_at=now(),
      used_store_code=p_store_code,
      tm_sale_id=p_tm_sale_id
  where id=v_row.id;

  return jsonb_build_object(
    'ok',true,
    'discountCode',v_row.discount_code,
    'pointsUsed',v_row.points,
    'discountAmount',v_row.discount_amount,
    'pointsAfter',coalesce((v_sync->>'balance')::integer,0),
    'usedAt',now()
  );
end;
$$;

grant execute
on function public.app_create_point_discount_ticket(integer)
to authenticated;

grant execute
on function public.tm_get_point_discount_ticket(text)
to authenticated;

grant execute
on function public.tm_complete_point_discount_ticket(text,text,text)
to authenticated;

notify pgrst,'reload schema';

commit;

select
  id,
  reward_enabled,
  discount_enabled,
  redeem_unit_points,
  redeem_unit_amount,
  max_discount_percent,
  min_order_amount,
  updated_at
from public.app_point_feature_settings
where id='default';
