-- 億家 App v0.10.8.2 商品專用兌換 QR
-- 請在 Supabase SQL Editor 執行一次。

create table if not exists public.app_redeem_tickets (
  id bigint generated by default as identity primary key,
  redeem_code text not null unique,
  auth_user_id uuid not null,
  member_phone text not null,
  member_product_id text not null,
  product_name text,
  quantity integer not null check (quantity > 0),
  status text not null default 'pending',
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  used_at timestamptz,
  used_store_code text,
  tm_sale_id text
);

create index if not exists idx_app_redeem_tickets_auth
  on public.app_redeem_tickets(auth_user_id, created_at desc);

create index if not exists idx_app_redeem_tickets_code_status
  on public.app_redeem_tickets(redeem_code, status);

alter table public.app_redeem_tickets enable row level security;

revoke all on public.app_redeem_tickets from anon, authenticated;

create or replace function public.app_create_redeem_ticket(
  p_member_product_id text,
  p_quantity integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_phone text;
  v_products jsonb;
  v_item jsonb;
  v_remaining integer;
  v_valid_until timestamptz;
  v_code text;
  v_expires timestamptz := now() + interval '600 seconds';
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  if p_quantity is null or p_quantity <= 0 then
    raise exception 'invalid quantity';
  end if;

  select phone
    into v_phone
  from public.app_members
  where auth_user_id = v_uid
  limit 1;

  if coalesce(v_phone,'') = '' then
    raise exception 'member not found';
  end if;

  select public.app_get_member_products()
    into v_products;

  if jsonb_typeof(v_products) <> 'array' then
    raise exception 'member products unavailable';
  end if;

  select e.value
    into v_item
  from jsonb_array_elements(v_products) e(value)
  where e.value->>'id' = p_member_product_id
  limit 1;

  if v_item is null then
    raise exception 'member product not found';
  end if;

  v_remaining := coalesce((v_item->>'remainingQuantity')::integer,0);

  if v_remaining <= 0 then
    raise exception 'product has no remaining quantity';
  end if;

  if p_quantity > v_remaining then
    raise exception 'quantity exceeds remaining quantity';
  end if;

  if nullif(v_item->>'validUntil','') is not null then
    v_valid_until := (v_item->>'validUntil')::timestamptz;
    if public.app_anybuy_is_expired(v_valid_until) then
      raise exception 'member product expired';
    end if;
  end if;

  -- 同一會員同一商品只保留最新一張有效兌換碼。
  update public.app_redeem_tickets
     set status = 'cancelled'
   where auth_user_id = v_uid
     and member_product_id = p_member_product_id
     and status = 'pending';

  loop
    v_code :=
      'YD'
      || to_char(clock_timestamp() at time zone 'Asia/Taipei','YYMMDDHH24MISSMS')
      || lpad((floor(random()*10000))::integer::text,4,'0');

    exit when not exists (
      select 1 from public.app_redeem_tickets where redeem_code = v_code
    );
  end loop;

  insert into public.app_redeem_tickets(
    redeem_code,
    auth_user_id,
    member_phone,
    member_product_id,
    product_name,
    quantity,
    status,
    expires_at
  )
  values(
    v_code,
    v_uid,
    v_phone,
    p_member_product_id,
    v_item->>'name',
    p_quantity,
    'pending',
    v_expires
  );

  return jsonb_build_object(
    'redeemCode', v_code,
    'memberPhone', v_phone,
    'memberProductId', p_member_product_id,
    'productName', coalesce(v_item->>'name','商品'),
    'quantity', p_quantity,
    'expiresAt', v_expires,
    'status', 'pending'
  );
end;
$$;

create or replace function public.tm_get_app_redeem_ticket(
  p_redeem_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.app_redeem_tickets%rowtype;
begin
  select *
    into v_row
  from public.app_redeem_tickets
  where redeem_code = trim(p_redeem_code)
  limit 1;

  if v_row.id is null then
    raise exception 'redeem ticket not found';
  end if;

  if v_row.status <> 'pending' then
    raise exception 'redeem ticket is not available';
  end if;

  if v_row.expires_at <= now() then
    update public.app_redeem_tickets
       set status = 'expired'
     where id = v_row.id;
    raise exception 'redeem ticket expired';
  end if;

  return jsonb_build_object(
    'redeemCode', v_row.redeem_code,
    'memberPhone', v_row.member_phone,
    'memberProductId', v_row.member_product_id,
    'productName', v_row.product_name,
    'quantity', v_row.quantity,
    'expiresAt', v_row.expires_at,
    'status', v_row.status
  );
end;
$$;

create or replace function public.tm_complete_app_redeem_ticket(
  p_redeem_code text,
  p_store_code text,
  p_tm_sale_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.app_redeem_tickets%rowtype;
begin
  select *
    into v_row
  from public.app_redeem_tickets
  where redeem_code = trim(p_redeem_code)
  for update;

  if v_row.id is null then
    raise exception 'redeem ticket not found';
  end if;

  if v_row.status = 'used' then
    raise exception 'redeem ticket already used';
  end if;

  if v_row.status <> 'pending' then
    raise exception 'redeem ticket is not available';
  end if;

  if v_row.expires_at <= now() then
    update public.app_redeem_tickets
       set status = 'expired'
     where id = v_row.id;
    raise exception 'redeem ticket expired';
  end if;

  update public.app_redeem_tickets
     set status = 'used',
         used_at = now(),
         used_store_code = p_store_code,
         tm_sale_id = p_tm_sale_id
   where id = v_row.id;

  return jsonb_build_object(
    'ok', true,
    'redeemCode', v_row.redeem_code,
    'status', 'used',
    'usedAt', now()
  );
end;
$$;

grant execute on function public.app_create_redeem_ticket(text,integer) to authenticated;
grant execute on function public.tm_get_app_redeem_ticket(text) to authenticated;
grant execute on function public.tm_complete_app_redeem_ticket(text,text,text) to authenticated;

notify pgrst, 'reload schema';
