
-- 億家 App v0.9.2
-- 新增「店舖結帳」待付款訂單
-- 線上支付開發測試仍沿用 dev_app_purchase_anybuy()

create table if not exists public.app_checkout_orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique,
  auth_user_id uuid not null,
  phone text not null,
  payment_method text not null,
  status text not null default 'pending_store_payment',
  total_amount numeric(10,2) not null default 0,
  expires_at timestamptz,
  paid_at timestamptz,
  paid_store_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_checkout_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.app_checkout_orders(id) on delete cascade,
  product_code text not null,
  product_name text not null,
  unit_price numeric(10,2) not null default 0,
  cart_qty integer not null check (cart_qty > 0),
  bundle_quantity integer not null default 1 check (bundle_quantity > 0),
  validity_days integer not null default 0,
  line_amount numeric(10,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_checkout_orders_user
  on public.app_checkout_orders(auth_user_id, created_at desc);

create index if not exists idx_app_checkout_orders_code
  on public.app_checkout_orders(order_code);

create index if not exists idx_app_checkout_order_items_order
  on public.app_checkout_order_items(order_id);

alter table public.app_checkout_orders enable row level security;
alter table public.app_checkout_order_items enable row level security;

-- 會員可讀自己的訂單；目前 App 不直接 insert/update，寫入交給 RPC
grant select on public.app_checkout_orders to authenticated;
grant select on public.app_checkout_order_items to authenticated;

drop policy if exists "app_checkout_orders_self_select" on public.app_checkout_orders;
create policy "app_checkout_orders_self_select"
on public.app_checkout_orders
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "app_checkout_order_items_self_select" on public.app_checkout_order_items;
create policy "app_checkout_order_items_self_select"
on public.app_checkout_order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.app_checkout_orders o
    where o.id = app_checkout_order_items.order_id
      and o.auth_user_id = auth.uid()
  )
);

create or replace function public.app_create_store_checkout_order(
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_phone text;
  v_order_id bigint;
  v_order_code text;
  v_total numeric(10,2) := 0;
  v_expires timestamptz := now() + interval '24 hours';
  v_item jsonb;
  v_product jsonb;
  v_product_key text;
  v_cart_qty integer;
  v_name text;
  v_price numeric(10,2);
  v_bundle_qty integer;
  v_validity_days integer;
  v_line numeric(10,2);
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 then
    raise exception 'cart is empty';
  end if;

  select phone into v_phone
  from public.app_members
  where auth_user_id = v_uid
  limit 1;

  if v_phone is null then
    raise exception 'member profile not found';
  end if;

  v_order_code :=
    'YS' ||
    to_char(clock_timestamp(),'YYMMDDHH24MISS') ||
    lpad((floor(random()*1000))::int::text,3,'0');

  insert into public.app_checkout_orders
    (order_code, auth_user_id, phone, payment_method, status,
     total_amount, expires_at, created_at, updated_at)
  values
    (v_order_code, v_uid, v_phone, 'store',
     'pending_store_payment', 0, v_expires, now(), now())
  returning id into v_order_id;

  for v_item in
    select value from jsonb_array_elements(p_items)
  loop
    v_product_key := nullif(v_item->>'productKey','');
    v_cart_qty := greatest(1,coalesce(nullif(v_item->>'cartQty','')::integer,1));

    select elem into v_product
    from public.yijia_app_state s,
         lateral jsonb_array_elements(s.data::jsonb) elem
    where s.store_id='001'
      and s.data_key='yj_app_anybuy_products'
      and coalesce((elem->>'active')::boolean,true)=true
      and (
        elem->>'code'=v_product_key
        or elem->>'id'=v_product_key
      )
    limit 1;

    if v_product is null then
      raise exception 'product not found or inactive: %', v_product_key;
    end if;

    v_name := coalesce(v_product->>'name','商品');
    v_price := coalesce(nullif(v_product->>'price','')::numeric,0);
    v_bundle_qty := greatest(1,coalesce(nullif(v_product->>'quantity','')::integer,1));
    v_validity_days := greatest(0,coalesce(nullif(v_product->>'validityDays','')::integer,0));
    v_line := v_price * v_cart_qty;

    insert into public.app_checkout_order_items
      (order_id, product_code, product_name, unit_price,
       cart_qty, bundle_quantity, validity_days, line_amount)
    values
      (v_order_id,
       coalesce(v_product->>'code',v_product_key),
       v_name,
       v_price,
       v_cart_qty,
       v_bundle_qty,
       v_validity_days,
       v_line);

    v_total := v_total + v_line;
  end loop;

  update public.app_checkout_orders
  set total_amount=v_total, updated_at=now()
  where id=v_order_id;

  return jsonb_build_object(
    'orderId',v_order_id,
    'orderCode',v_order_code,
    'totalAmount',v_total,
    'status','pending_store_payment',
    'paymentMethod','store',
    'expiresAt',v_expires
  );
end;
$$;

revoke all on function public.app_create_store_checkout_order(jsonb) from public;
grant execute on function public.app_create_store_checkout_order(jsonb) to authenticated;

notify pgrst, 'reload schema';
