
-- 億家 App v0.7
-- 隨買商品 / 我的商品 / 兌換紀錄

create extension if not exists pgcrypto;

create table if not exists public.app_products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  price numeric(10,2) not null default 0 check (price >= 0),
  image_url text,
  is_active boolean not null default true,
  sale_start timestamptz,
  sale_end timestamptz,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_member_products (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  phone text not null,
  product_id uuid not null references public.app_products(id),
  quantity_total integer not null check (quantity_total > 0),
  quantity_remaining integer not null check (quantity_remaining >= 0),
  purchased_at timestamptz not null default now(),
  expires_at timestamptz,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (quantity_remaining <= quantity_total)
);

create table if not exists public.app_redemptions (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  member_product_id bigint not null references public.app_member_products(id),
  product_id uuid not null references public.app_products(id),
  quantity integer not null check (quantity > 0),
  store_code text,
  redeemed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_app_products_active_sort
  on public.app_products(is_active, sort_order);

create index if not exists idx_app_member_products_user
  on public.app_member_products(auth_user_id, purchased_at desc);

create index if not exists idx_app_redemptions_user
  on public.app_redemptions(auth_user_id, redeemed_at desc);

alter table public.app_products enable row level security;
alter table public.app_member_products enable row level security;
alter table public.app_redemptions enable row level security;

-- 顧客 App 可讀取上架商品
drop policy if exists "app_products_public_read_active" on public.app_products;
create policy "app_products_public_read_active"
on public.app_products for select
to authenticated
using (is_active = true);

-- 會員只能讀自己的已購商品
drop policy if exists "app_member_products_self_select" on public.app_member_products;
create policy "app_member_products_self_select"
on public.app_member_products for select
to authenticated
using (auth.uid() = auth_user_id);

-- 會員只能讀自己的兌換紀錄
drop policy if exists "app_redemptions_self_select" on public.app_redemptions;
create policy "app_redemptions_self_select"
on public.app_redemptions for select
to authenticated
using (auth.uid() = auth_user_id);

-- App 顧客端「不允許」自行 insert/update app_member_products 或 app_redemptions。
-- 之後購買成功與 TM 兌換，必須由安全後端 / SC / TM 流程寫入。

-- 可選：先放兩筆測試商品，方便確認 App 隨買頁能讀到商品
insert into public.app_products (name, description, price, sort_order)
select '大杯美式咖啡', '億家隨買跨店取', 45, 10
where not exists (select 1 from public.app_products where name='大杯美式咖啡');

insert into public.app_products (name, description, price, sort_order)
select '經典奶茶', '億家隨買跨店取', 35, 20
where not exists (select 1 from public.app_products where name='經典奶茶');
